import Head from "next/head";
import { ThemeProvider, CssBaseline } from '@mui/material';
import theme from '../../theme';
import Container from '../components/Container'
import { FactsContextProvider } from '../context/FactsContext'
import { Playfair_Display } from 'next/font/google'

const mainFontFamily = Playfair_Display({
  weight: ['400', '700'],
  subsets: ['latin']
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Metyis Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <div
          className={mainFontFamily.className}>
          <FactsContextProvider>
            <Container />
          </FactsContextProvider>
        </div>
      </ThemeProvider>

    </>
  );
}
